image: archlinux
packages:
  - clang
  - ffmpeg
  - libcap
  - libinput
  - libxkbcommon
  - mesa
  - meson
  - pixman
  - wayland
  - wayland-protocols
  - xcb-util-image
sources:
  - https://github.com/swaywm/wlroots
tasks:
  - setup: |
      mkdir wlroots/build-{gcc,clang}
      cd wlroots/build-gcc
      CC=gcc meson ..
      cd ../build-clang
      CC=clang meson ..
  - gcc: |
      cd wlroots/build-gcc
      ninja
  - clang: |
      cd wlroots/build-clang
      ninja
