sudo: required

services:
- docker

language: c

compiler:
  - gcc
  - clang

# Settings to try
env:
 matrix:
  - OPTIONS="-Denable_libcap=true  -Denable_systemd=true  -Denable_elogind=false -Denable_xwayland=true"
  - OPTIONS="-Denable_libcap=false -Denable_systemd=false -Denable_elogind=false -Denable_xwayland=false"

arch:
  packages:
    - meson
    - ninja
    - wayland
    - wayland-protocols
    - mesa
    - libinput
    - pixman
    - libxkbcommon
    - xcb-util-image
    - libcap
  script:
    - "meson build $OPTIONS"
    - "ninja -C build"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
