sudo: required

language: c

compiler:
  - gcc
  - clang

arch:
  packages:
    - meson
    - ninja
    - wayland
    - wayland-protocols
    - mesa
    - libinput
    - pixman
    - libxkbcommon
    - xcb-util-image
    - libcap
  script:
    - "meson build"
    - "ninja -C build"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
